baseURL = "https://napsterinblue.github.io/notes/"
languageCode = "en-us"
title = "Data Science Notes"
theme = "berbera"

pygmentsCodeFences=true
pygmentsUseClasses=true
canonifyURLs=true
publishDir="docs"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]
