name = "Berbera"
license = "GPL-3.0"
description = "A bootstrap 4 Hugo theme for notes."
tags = ["bootstrap", "blog", "font awesome"]
features = ["responsive", "blog"]
min_version = 0.25

[author]
  name = "Chris Albon"
  homepage = "https://chrisalbon.com"

[based on]
  name = "Alan Orth"
  homepage = "https://englishbulgaria.net"

[original]
  author = "mdo"
  homepage = "https://v4-alpha.getbootstrap.com/examples/blog/"
